move test to app

diff --git a/ansible/playbook.yaml b/ansible/playbook.yaml
--- a/ansible/playbook.yaml
+++ b/ansible/playbook.yaml
@@ -329,3 +329,103 @@
       become: true
       become_user: "{{ lookup('env', 'USER') }}"
       ansible.builtin.shell: 'echo "{{ elasticsearch_password.stdout }}" > /tmp/elasticsearch-password.txt'
+
+- name: build app
+  hosts: new_droplet
+  become: true
+  become_user: debian
+  environment:
+    KUBECONFIG: "{{ ansible_env.HOME }}/.kube/config"
+  tasks:
+    - name: create namespace
+      ansible.builtin.shell: |
+        # exit on errors
+        set -e
+        # load kubeconfig
+        export KUBECONFIG=~/.kube/config
+        # variables
+        INTERNAL_REGISTRY_URL="docker-registry.docker-registry.svc.cluster.local:5000"
+        IMAGE_TAG="app:0.0.1"
+        REPO_URL="https://github.com/brandonros/argocd-poc.git"
+        BRANCH_NAME="master"
+        BUILD_CONTEXT_DIRECTORY="./app/"
+        # clone repo to temp directory
+        WORK_DIR=$(mktemp -d -p /tmp)
+        git clone --depth=1 --branch "$BRANCH_NAME" "$REPO_URL" "$WORK_DIR"
+        # build json overrides for kaniko pod
+        OVERRIDES=$(
+        cat <<EOF
+        {
+          "apiVersion": "v1",
+          "spec": {
+            "containers": [
+              {
+                "name": "kaniko",
+                "image": "gcr.io/kaniko-project/executor:latest",
+                "stdin": true,
+                "stdinOnce": true,
+                "args": [
+                  "--dockerfile=Dockerfile",
+                  "--context=tar://stdin",
+                  "--destination=$INTERNAL_REGISTRY_URL/$IMAGE_TAG"
+                ]
+              }
+            ]
+          }
+        }
+        EOF
+        )
+        # make sure kaniko namespace exists
+        kubectl create namespace kaniko --dry-run=client -o yaml | kubectl apply -f -
+        # tar context and send to kubectl run which will pull kaniko executor image
+        RANDOM_BYTES=$(echo $RANDOM | md5sum | head -c 10)
+        POD_NAME="kaniko-$RANDOM_BYTES"
+        DIRECTORY=$(realpath "$WORK_DIR/$BUILD_CONTEXT_DIRECTORY")
+        tar --create --file=- --verbose --directory="$DIRECTORY" --gzip --verbose index.mjs package.json package-lock.json Dockerfile .dockerignore | kubectl run -n kaniko \
+          "$POD_NAME" \
+          --rm \
+          --stdin=true \
+          --image=gcr.io/kaniko-project/executor:latest \
+          --restart=Never \
+          --overrides="$OVERRIDES"
+        # cleanup
+        rm -rf "$WORK_DIR"
+
+- name: deploy app
+  hosts: new_droplet
+  become: true
+  become_user: debian
+  environment:
+    KUBECONFIG: "{{ ansible_env.HOME }}/.kube/config"
+  tasks:
+    - name: create namespace
+      ansible.builtin.shell: |
+        # exit on errors
+        set -e
+        # load kubeconfig
+        export KUBECONFIG=~/.kube/config
+        # get registry IP
+        DOCKER_REGISTRY_CLUSTER_IP=$(kubectl -n docker-registry get service/docker-registry -o=jsonpath='{.spec.clusterIP}')
+        PORT=5000
+        EXTERNAL_REGISTRY_URL="$DOCKER_REGISTRY_CLUSTER_IP:$PORT" # do not use kubernetes internal DNS because kubernetes node does not pull from pod context aka no access to internal DNS
+        # variables
+        IMAGE_TAG="app:0.0.1"
+        # create namespace
+        kubectl create namespace app --dry-run=client -o yaml | kubectl apply -f -
+        # deploy
+        ELASTICSEARCH_USERNAME=$(kubectl -n elk get secret elasticsearch-master-credentials -o json | jq -r '.data.username' | base64 -d)
+        ELASTICSEARCH_PASSWORD=$(kubectl -n elk get secret elasticsearch-master-credentials -o json | jq -r '.data.password' | base64 -d)
+        argocd app create app \
+          --repo "https://github.com/brandonros/argocd-poc.git" \
+          --path ./app/helm/ \
+          --dest-namespace app \
+          --dest-server https://kubernetes.default.svc \
+          --revision-history-limit 1 \
+          --helm-set image.repository="$EXTERNAL_REGISTRY_URL" \
+          --helm-set image.tag="$IMAGE_TAG" \
+          --helm-set env.ELASTICSEARCH_USERNAME="$ELASTICSEARCH_USERNAME" \
+          --helm-set env.ELASTICSEARCH_PASSWORD="$ELASTICSEARCH_PASSWORD" \
+          --helm-set env.ELASTICSEARCH_URL="https://elasticsearch-master-headless.elk.svc.cluster.local:9200" \
+          --upsert
+        argocd app sync app && argocd app wait app
+
